// Alert
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// Auth
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT = 'LOGOUT';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';

// Profile
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILES = 'GET_PROFILES';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const PROFILE_LOADING = 'PROFILE_LOADING';
export const PROFILES_LOADING = 'PROFILES_LOADING';
export const GET_PROFILE_SEARCH = 'GET_PROFILE_SEARCH';
export const CLEAR_PROFILE_SEARCH = 'CLEAR_PROFILE_SEARCH';
export const ADD_PROFILE_CONTACT = 'ADD_PROFILE_CONTACT';
export const REMOVE_PROFILE_CONTACT = 'REMOVE_PROFILE_CONTACT';

// Chat
export const CREATE_CHAT = 'CREATE_CHAT';
export const GET_CHAT = 'GET_CHAT';
export const GET_CHAT_BOOKMARKS = 'GET_CHAT_BOOKMARKS';
export const GET_CHAT_PARTICIPANTS = 'GET_CHAT_PARTICIPANTS';
export const GET_CHATS = 'GET_CHATS';
export const EDIT_CHAT = 'EDIT_CHAT';
export const EDIT_BOOKMARKS = 'EDIT_BOOKMARKS';
export const DELETE_CHAT = 'DELETE_CHAT';
export const CHAT_ERROR = 'CHAT_ERROR';
export const CLEAR_CHAT = 'CLEAR_CHAT';

// Message
export const CREATE_MESSAGE = 'CREATE_MESSAGE';
export const GET_MESSAGE = 'GET_MESSAGE';
export const GET_MESSAGES = 'GET_MESSAGES';
export const EDIT_MESSAGE = 'EDIT_MESSAGE';
export const DELETE_MESSAGE = 'DELETE_MESSAGE';
export const MESSAGE_ERROR = 'MESSAGE_ERROR';
export const CREATE_MESSAGE_ERROR = 'CREATE_MESSAGE_ERROR';
export const SELECT_MESSAGE = 'SELECT_MESSAGE';
export const DESELECT_MESSAGE = 'DESELECT_MESSAGE';
export const CLEAR_SELECTED = 'CLEAR_SELECTED';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';
export const MESSAGE_RESET = 'MESSAGE_RESET';
